server:
  port: 8182
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms

spring:
  application:
    name: ${project.artifactId}
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    dynamic:
      druid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 60000
        validation-query: select 'x'
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        filters: stat,wall
        share-prepared-statements: true
      primary: master
      datasource:
        master:
          username: root
          password: hyx123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.8:3306/dubbo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          druid:
            #select 1 FROM DUAL
            validation-query: select 'x'
        slave_1:
          username: root
          password: hyx123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.8:3306/dubbo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          druid:
            # select 1 FROM DUAL
            validation-query: select 'x'
        slave_2:
          username: root
          password: hyx123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.8:3306/dubbo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          druid:
            # select 1 FROM DUAL
            validation-query: select 'x'
  redis:
    database: 0
    host: 192.168.1.8
    port: 6379
    password: hyx123456
    timeout: 3600ms
    #    cluster:
    #      max-redirects: 3
    #      nodes: 192.168.1.8:7000, 192.168.1.8:7001, 192.168.1.8:7002, 192.168.1.8:7003, 192.168.1.8:7004,192.168.1.8:7005
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
        max-wait: 6000ms
      shutdown-timeout: 100ms

  session:
    store-type: redis
#  activemq:
#    broker-url: tcp://192.168.1.8:8161
#    user: admin
#    password: admin
#    in-memory: true
#    pool:
#      enabled: true
#      max-connections: 100
#      idle-timeout: 30s
  rabbitmq:
    host: 192.168.1.8
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
  boot:
    admin:
      client:
        url: http://192.168.1.8:8180
        instance:
          service-base-url: http://192.168.1.8:${server.port}
          management-base-url: http://192.168.1.8:${server.port}

mybatis-plus:
  mapper-locations: classpath*:com/hdw/*/mapper/sqlMapperXml/*Mapper.xml
  type-aliases-package: com.hdw.*.entity
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

dubbo:
  application:
    id: upms-consumer
    name: ${dubbo.application.id}
    qos-enable: true
    qos-port: 22222
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: client
    threadpool: fixed
    threads: 200
    payload: 52428800
  registry:
    id: registry
    address: zookeeper://192.168.1.8:2181
    file: /output/cache/upms-consumer.cache
    timeout: 5000
    session: 60000
    check: true
  consumer:
    id: ${dubbo.application.id}
    protocol: ${dubbo.protocol.id}
    group: upms
    version: 1.0.0
    timeout: 60000
    loadbalance: roundrobin
    retries: 2
    actives: 200
    executes: 200

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    dubbo:
      enable: true
      dubbo-shutdown.enabled: true
      dubbo-configs.enabled: true
      dubbo-services.enabled: true
      dubbo-references.enabled: true
      dubbo-properties.enabled: true
  health:
    dubbo:
      status:
        defaults: memory,load
        extras: registry,load,threadpool

info:
  name: 基础平台WEB服务
  version: 1.0.0

fdfs:
  file-upload:
    server: http://192.168.1.8:9090
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:
    width: 150
    height: 150
  trackerList[0]: 192.168.1.8:22122

hdw:
  expire: 1800
  upms:
    loginUrl: /login
    successUrl: /index
    unauthorizedUrl: /unauth
    #shiro、jwt、cas
    type: jwt
  shiro:
    session: dubbo-shiro-session-
    cache: dubbo-shiro-cache-
    cookie: /dubbo
  scheduler:
    name: dubbo-
  file-upload:
    prefix: D:\\Workspaces\\GBICC\\src\\dubbo\\upms-web\\src\main\\resources\\static
    server: http://192.168.1.8
  redisson:
    model: single

#CAS Config
cas:
  prefixUrl: http://192.168.1.8:8443/cas
  loginUrl: ${cas.prefixUrl}/login
  logoutUrl: ${cas.prefixUrl}/logout
  serviceUrl: http://192.168.1.8:${server.port}/
  callbackUrl: ${cas.serviceUrl}/callback
  salt: 12345678901234567890123456789012
  serverUrlPrefix: http://192.168.1.8:8443/cas


